language: node_js
node_js:
  - 'stable'
git:
  submodules: true
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
before_script:
  - npm -g install firebase-tools
  - npm -g install gatsby
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm run test:ci
  - npm run coverage:ci
  - npm run build:ci
after_script:
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy:ci
on:
  branch: master
